
#----------------------------------------------------------------------------------------------------------------------#
#
#                                                       Dexterity by c7dev
#
#    Thank you for downloading Dexterity! This plugin is intended to make your worlds pop with the power of block displays. 
#    Using a worldedit-like interface, you can easily move, scale, rotate, and animate block displays without the hassle!
#
#   If you need help or have a question, join the discord: https://discord.gg/yx9hUByTzq
#
#   Please consider writing a review if you like the plugin :D
#
#----------------------------------------------------------------------------------------------------------------------#

lang-file: "en-US.yml"
primary-color: "#7a8c86" #Default: #7a8c86
secondary-color: "#21de80" #Default: #21de80
tertiary-color: "#42f5ef" #Default: #42f5ef

max-selection-volume: 25000 #for tps safety
highlight-display-on-select: true #temporary glow effect when clicked with wand
session-history-size: 25 #maximum number of transactions to store