name: Dexterity
version: 1.0.8
author: c7dev
main: me.c7dev.dexterity.Dexterity
api-version: 1.19
load: POSTWORLD
softdepend: [WorldEdit]

commands:
  dex:
    aliases: [d, dexterity]
    description: Dexterity main command